---
title: "Prepairing Data"
output: html_notebook
---
$\bf Transcription Factor$

```{r}
system(" wget http://humantfs.ccbr.utoronto.ca/download/v_1.01/Fig4A.csv ")
system(" mv Fig4A.csv TF.csv")
TF_data <- read.csv(file="TF.csv", header=TRUE, sep=",")
```


 $\bf mRNA$  $\bf Data$ $\bf (GTEx)$ 
```{r}

library(R.utils)
system(" wget 'https://storage.googleapis.com/gtex_analysis_v7/single_tissue_eqtl_data/GTEx_Analysis_v7_eQTL_expression_matrices.tar.gz' ")
system(" tar -xvzf GTEx_Analysis_v7_eQTL_expression_matrices.tar.gz ")
system(" rm -rf GTEx_Analysis_v7_eQTL_expression_matrices/*.tbi")

mRNA_path <- "GTEx_Analysis_v7_eQTL_expression_matrices"

files <- list.files(path=mRNA_path, pattern="*.gz", full.names=TRUE, recursive=FALSE)
for (file in files){
  filename <- file
  gunzip(filename, destname = gsub("[.]gz$", "", filename), overwrite = FALSE, remove = TRUE, BFR.SIZE = 1e+07)
}
```


```{r}
files <- list.files(path=mRNA_path, pattern="*.bed", full.names=TRUE, recursive=FALSE)
for (file in files){
  filename <- file
  bed <- read.table(filename,header = TRUE, sep="\t",stringsAsFactors=FALSE, quote="")
  #analysis
}

```


 $\bf egene$  $\bf Data$ $\bf (GTEx)$ 
```{r}

system(" wget 'https://storage.googleapis.com/gtex_analysis_v7/single_tissue_eqtl_data/GTEx_Analysis_v7_eQTL.tar.gz' ")
system(" tar -xvzf GTEx_Analysis_v7_eQTL.tar.gz ")
system(" rm -rf GTEx_Analysis_v7_eQTL/*signi*")

eGene_path <- "GTEx_Analysis_v7_eQTL/"

files <- list.files(path=eGene_path, pattern="*.gz", full.names=TRUE, recursive=FALSE)
for (file in files){
  filename <- file
  gunzip(filename, destname = gsub("[.]gz$", "", filename), overwrite = FALSE, remove = TRUE, BFR.SIZE = 1e+07)
}

```


```{r}

files <- list.files(path=eGene_path, pattern="*.txt", full.names=TRUE, recursive=FALSE)
for (file in files){
  filename <- file
  bed <- read.delim(filename,header = TRUE)
  
}

```

