---
title: "glasso-rmarkdown"
author: "Maryam"
date: "May 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Loading glasso and requirements


```{r glasso}
library(glasso)
library(Matrix)
library(expm)
source("../../ClassComparison_3.1.7/ClassComparison/R/cc03-fastlm.R")
dyn.load("../src/glasso.so")
```

### Laoding synthetic data 

```{r csv}
y <- read.table("y.csv")
y <- array(c(y$V1), dim = c(30, 100, 1))

x <- read.table("X.csv")
x <- array(c(x$V1), dim = c(30, 100, 1000))
```

### Creating first S and $\Omega$

```{r omega}
myglasso <- function(S){
    zero<-matrix(c(sample(1:50, 60, replace = TRUE)),ncol=2,byrow=TRUE)
    a<-glasso(S,0,zero=zero) #rho?
    #print(a)
    return(a$w)
}
n <- 100  
A <- matrix(runif(n^2)*2-1, ncol=n) 
S <- t(A) %*% A
omega <- myglasso(S)
omega2 <- sqrtm(omega)
```
### Multiplying $\Omega ^ {1/2}$ in $y_i$ and $X_i$

```{r mul}
Y <- array(dim = dim(y))
for(i in 1:dim(y)[1]){
    Y[i,,] <- omega2 %*% y[i,,]
}
X <- array(dim = dim(x))
for(i in 1:dim(X)[1]){
    X[i,,] <- omega2 %*% x[i,,]
}
```
### Running glasso #niter times
```{r}

```
### Testing MultiLinearModel
```{r test ml}

Xflat = matrix(X, dim(X)[1], dim(X)[2] * dim(X)[3])
print(dim(Xflat))
Yflat = matrix(Y, dim(Y)[1], dim(Y)[2])
print(dim(Yflat))
xnam <- paste0("x", 1:100)
#model <- MultiLinearModel(form = as.formula(paste("y ~ ", paste(xnam, collapse= "+"))), clindata = Yflat , arraydata = t(Xflat))
```